// Generated by https://quicktype.io

export interface Person {
	resourceName: string
	etag: string
	names: Name[]
	photos: Photo[]
	emailAddresses: EmailAddress[]
}

export interface EmailAddress {
	metadata: EmailAddressMetadata
	value: string
}

export interface EmailAddressMetadata {
	primary?: boolean
	verified: boolean
	source: Source
	sourcePrimary?: boolean
}

export interface Source {
	type: string
	id: string
}

export interface Name {
	metadata: NameMetadata
	displayName: string
	familyName: string
	givenName: string
	displayNameLastFirst: string
	unstructuredName: string
}

export interface NameMetadata {
	primary?: boolean
	source: Source
}

export interface Photo {
	metadata: NameMetadata
	url: string
}
